# CMake generated Testfile for 
# Source directory: C:/Users/A/Documents/Codex/2026-09-11/v/outputs/AxiomChess
# Build directory: C:/Users/A/Documents/Codex/2026-09-11/v/outputs/AxiomChess/build-asan
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("axiom_tests" "C:/Users/A/Documents/Codex/2026-09-11/v/outputs/AxiomChess/build-asan/Debug/axiom_tests.exe")
  set_tests_properties("axiom_tests" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/A/Documents/Codex/2026-09-11/v/outputs/AxiomChess/CMakeLists.txt;45;add_test;C:/Users/A/Documents/Codex/2026-09-11/v/outputs/AxiomChess/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("axiom_tests" "C:/Users/A/Documents/Codex/2026-09-11/v/outputs/AxiomChess/build-asan/Release/axiom_tests.exe")
  set_tests_properties("axiom_tests" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/A/Documents/Codex/2026-09-11/v/outputs/AxiomChess/CMakeLists.txt;45;add_test;C:/Users/A/Documents/Codex/2026-09-11/v/outputs/AxiomChess/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("axiom_tests" "C:/Users/A/Documents/Codex/2026-09-11/v/outputs/AxiomChess/build-asan/MinSizeRel/axiom_tests.exe")
  set_tests_properties("axiom_tests" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/A/Documents/Codex/2026-09-11/v/outputs/AxiomChess/CMakeLists.txt;45;add_test;C:/Users/A/Documents/Codex/2026-09-11/v/outputs/AxiomChess/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("axiom_tests" "C:/Users/A/Documents/Codex/2026-09-11/v/outputs/AxiomChess/build-asan/RelWithDebInfo/axiom_tests.exe")
  set_tests_properties("axiom_tests" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/A/Documents/Codex/2026-09-11/v/outputs/AxiomChess/CMakeLists.txt;45;add_test;C:/Users/A/Documents/Codex/2026-09-11/v/outputs/AxiomChess/CMakeLists.txt;0;")
else()
  add_test("axiom_tests" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("axiom_audit" "C:/Users/A/Documents/Codex/2026-09-11/v/outputs/AxiomChess/build-asan/Debug/axiom_audit.exe")
  set_tests_properties("axiom_audit" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/A/Documents/Codex/2026-09-11/v/outputs/AxiomChess/CMakeLists.txt;49;add_test;C:/Users/A/Documents/Codex/2026-09-11/v/outputs/AxiomChess/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("axiom_audit" "C:/Users/A/Documents/Codex/2026-09-11/v/outputs/AxiomChess/build-asan/Release/axiom_audit.exe")
  set_tests_properties("axiom_audit" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/A/Documents/Codex/2026-09-11/v/outputs/AxiomChess/CMakeLists.txt;49;add_test;C:/Users/A/Documents/Codex/2026-09-11/v/outputs/AxiomChess/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("axiom_audit" "C:/Users/A/Documents/Codex/2026-09-11/v/outputs/AxiomChess/build-asan/MinSizeRel/axiom_audit.exe")
  set_tests_properties("axiom_audit" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/A/Documents/Codex/2026-09-11/v/outputs/AxiomChess/CMakeLists.txt;49;add_test;C:/Users/A/Documents/Codex/2026-09-11/v/outputs/AxiomChess/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("axiom_audit" "C:/Users/A/Documents/Codex/2026-09-11/v/outputs/AxiomChess/build-asan/RelWithDebInfo/axiom_audit.exe")
  set_tests_properties("axiom_audit" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/A/Documents/Codex/2026-09-11/v/outputs/AxiomChess/CMakeLists.txt;49;add_test;C:/Users/A/Documents/Codex/2026-09-11/v/outputs/AxiomChess/CMakeLists.txt;0;")
else()
  add_test("axiom_audit" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("axiom_calibration" "C:/Users/A/Documents/Codex/2026-09-11/v/outputs/AxiomChess/build-asan/Debug/axiom_calibration.exe")
  set_tests_properties("axiom_calibration" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/A/Documents/Codex/2026-09-11/v/outputs/AxiomChess/CMakeLists.txt;53;add_test;C:/Users/A/Documents/Codex/2026-09-11/v/outputs/AxiomChess/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("axiom_calibration" "C:/Users/A/Documents/Codex/2026-09-11/v/outputs/AxiomChess/build-asan/Release/axiom_calibration.exe")
  set_tests_properties("axiom_calibration" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/A/Documents/Codex/2026-09-11/v/outputs/AxiomChess/CMakeLists.txt;53;add_test;C:/Users/A/Documents/Codex/2026-09-11/v/outputs/AxiomChess/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("axiom_calibration" "C:/Users/A/Documents/Codex/2026-09-11/v/outputs/AxiomChess/build-asan/MinSizeRel/axiom_calibration.exe")
  set_tests_properties("axiom_calibration" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/A/Documents/Codex/2026-09-11/v/outputs/AxiomChess/CMakeLists.txt;53;add_test;C:/Users/A/Documents/Codex/2026-09-11/v/outputs/AxiomChess/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("axiom_calibration" "C:/Users/A/Documents/Codex/2026-09-11/v/outputs/AxiomChess/build-asan/RelWithDebInfo/axiom_calibration.exe")
  set_tests_properties("axiom_calibration" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/A/Documents/Codex/2026-09-11/v/outputs/AxiomChess/CMakeLists.txt;53;add_test;C:/Users/A/Documents/Codex/2026-09-11/v/outputs/AxiomChess/CMakeLists.txt;0;")
else()
  add_test("axiom_calibration" NOT_AVAILABLE)
endif()
